### ISSUE TITLE
When filter is selected on a column, the refresh button continues to spin even after filter is complete. 

### ISSUE THREAD

**Issue by DavidGeeraerts** [caarmen/network-monitor#66] opened 2015-08-06 15:25 UTC
Not sure if the behavior is as intended. When selecting a filter on a column, and the filter is applied, the refresh button continues to spin even after the filtering seems to be complete. I'm wondering if the application is continuously trying to update, perhaps consuming more CPU cycles, and in turn consuming more battery.
P.S. Thank you for creating such an awesome Android application; now I can keep tabs on my service provider [Comcast <-- who sucks] and have 'evidence' when their service is down. Again, much appreciated, and a thank you for posting on F-Droid repository!

**Comment by caarmen** [comment] 2015-08-08 16:26
Hello David.

Thanks for the feedback.  Could you give me some additional info? Because I can't seem to reproduce the bug on my end.  On my end, the refresh button spins after applying a filter, but only for a couple of seconds, until the page finishes loading.

* Phone model
* Android version
* Network Monitor version
* What filters did you apply?
* What do you have for the setting for "number of rows"? 

Many thanks :) Hope I can get to the bottom of this bug!

Cheers

**Comment by DavidGeeraerts** [comment] 2015-08-11 20:10
The 'issue' observed happened on a Google Nexus 10 [tablet] with Android 5.1.x with Network Monitor version 1.22.0; the filter applied was on the adapter column, filtering to have WLAN only --no blanks, no p*. The number of rows was set to 100.
I'll have to see if I can reproduce the issue, and retest with the latest version of Network Monitor.

Hope this helpful. 

David

**Comment by DavidGeeraerts** [comment] 2015-08-12 15:06
With the latest version of Network Monitor v. 1.22.1 on the same device [Google Nexus 10] the issue was not reproducible. Perhaps just a glitch on the older version.

**Comment by caarmen** [comment] 2015-08-15 10:58
Hi David,
Thanks for the additional info.  I tried out the wlan filter and also couldn't reproduce the bug.

I'll close this issue for now, but please don't hesitate to reopen it if you see it again.

Cheers,
Carmen

**Closed by caarmen** 2015-08-15 10:58 UTC
