### ISSUE TITLE
Allow changing sort order of data

### ISSUE THREAD

**Issue by ab1jx** [caarmen/network-monitor#69] opened 2015-10-05 18:31 UTC
I want to plot with Gnuplot, which as I recall basically connects data points in the order in which they appear in the data file.  I want them chronologically sorted, not in order of inverse signal strength or some such.  I gave up and wrote something to preprocess the data anyway because I was having trouble getting the dates and times to work in Gnuplot.

Great app though, most of the time my cell signal is at -95 dbm or worse.  The strength varies by itself without even moving the phone.  I'm a ham, and it's good to have something more quantitative than a number of bars.

So enhancement, by all means, for this one.

**Comment by caarmen** [comment] 2015-10-05 18:35
Hello ab1jx,

Note that in the app, in the log view, you can tap on a column name to sort the data by that column.

Could you please clarify something?  I'm not sure exactly what this request is for:

1) Do you want a new function to export the data to Gnuplot?
2) Do you want to modify one of the existing exports (CSV?) so that the export is sorted based on the column the user selected in the log view?

Many thanks,
Carmen

**Comment by ab1jx** [comment] 2015-10-05 19:44
Does changing it in the GUI affect the way it's output?  I didn't try that.

The order is only important for "dumb" programs like Gnuplot, for
feeding to most real database programs like PostgreSQL, SqlLite, MS
Access the database can do the sort with an "order by" clause when
querying it.  Creating a new SqlLite database each day might be an
option, it's pretty universal and lightweight.

In theory I thought Gnuplot could import your dates and times since
it's pretty flexible but I'm out of practice and gave up after an hour
or so of fighting with it.  Easier (and more fun) to just write
something.

I was running a cron job on a unix machine that called hping and used
Gnuplot to make a plot each day but it didn't have access to fields
like dbm and asu.  The biggest problem was that when I was using the
network my loading affected the measurements.  The only internet
connection I've got is through a cell phone (or dial up), I use USB or
WiFi tethering off that.

I don't get a lot of signal, but it seems like the internet
performance is even worse.  AT&T towers in a rural area, I'm not sure
what the root of the problem is.  Possibly just overloading.

On 10/5/15, Carmen Alvarez <notifications@github.com> wrote:
> Hello ab1jx,
>
> Note that in the app, in the log view, you can tap on a column name to sort
> the data by that column.
>
> Could you please clarify something?  I'm not sure exactly what this request
> is for:
>
> 1) Do you want a new function to export the data to Gnuplot?
> 2) Do you want to modify one of the existing exports (CSV?) so that the
> export is sorted based on the column the user selected in the log view?
>
> Many thanks,
> Carmen
>
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/caarmen/network-monitor/issues/69#issuecomment-145625228


-- 
Credit is the root of all evil.  - AB1JX

**Comment by ab1jx** [comment] 2015-10-06 02:46
Maybe I see why Gnuplot isn't working.  In some places in the CSV file
there's something like:

2015-10-0004 05:46:0020,FAIL,FAIL,HSPAP,CONNECTED,1,1,0,CONNECTED,connecte
d,AT&T,310,410,1,0,-109,2,0,131779038,2010,51678,6994,33,92

Notice the 4-digit day of month and also second.  This is what Gnuplot
complained about and it was also crashing a C program I wrote that
uses strptime() to try to parse the dates and times.  It doesn't
happen on every line, or every log file.

You may have fixed this, I'm running version 1.22.0 from f-droid
because I got an error installing the latest version they had.
Android 5.02 on a Motorola Moto-e2


On 10/5/15, Alan Corey <alan01346@gmail.com> wrote:
> Does changing it in the GUI affect the way it's output?  I didn't try that.
>
> The order is only important for "dumb" programs like Gnuplot, for
> feeding to most real database programs like PostgreSQL, SqlLite, MS
> Access the database can do the sort with an "order by" clause when
> querying it.  Creating a new SqlLite database each day might be an
> option, it's pretty universal and lightweight.
>
> In theory I thought Gnuplot could import your dates and times since
> it's pretty flexible but I'm out of practice and gave up after an hour
> or so of fighting with it.  Easier (and more fun) to just write
> something.
>
> I was running a cron job on a unix machine that called hping and used
> Gnuplot to make a plot each day but it didn't have access to fields
> like dbm and asu.  The biggest problem was that when I was using the
> network my loading affected the measurements.  The only internet
> connection I've got is through a cell phone (or dial up), I use USB or
> WiFi tethering off that.
>
> I don't get a lot of signal, but it seems like the internet
> performance is even worse.  AT&T towers in a rural area, I'm not sure
> what the root of the problem is.  Possibly just overloading.
>
> On 10/5/15, Carmen Alvarez <notifications@github.com> wrote:
>> Hello ab1jx,
>>
>> Note that in the app, in the log view, you can tap on a column name to
>> sort
>> the data by that column.
>>
>> Could you please clarify something?  I'm not sure exactly what this
>> request
>> is for:
>>
>> 1) Do you want a new function to export the data to Gnuplot?
>> 2) Do you want to modify one of the existing exports (CSV?) so that the
>> export is sorted based on the column the user selected in the log view?
>>
>> Many thanks,
>> Carmen
>>
>> ---
>> Reply to this email directly or view it on GitHub:
>> https://github.com/caarmen/network-monitor/issues/69#issuecomment-145625228
>
>
> --
> Credit is the root of all evil.  - AB1JX
>


-- 
Credit is the root of all evil.  - AB1JX

**Comment by ab1jx** [comment] 2015-10-06 02:49
And yes, changing the sort order in the GUI seems to change the CSV
file sort order too.

On 10/5/15, Alan Corey <alan01346@gmail.com> wrote:
> Maybe I see why Gnuplot isn't working.  In some places in the CSV file
> there's something like:
>
> 2015-10-0004 05:46:0020,FAIL,FAIL,HSPAP,CONNECTED,1,1,0,CONNECTED,connecte
> d,AT&T,310,410,1,0,-109,2,0,131779038,2010,51678,6994,33,92
>
> Notice the 4-digit day of month and also second.  This is what Gnuplot
> complained about and it was also crashing a C program I wrote that
> uses strptime() to try to parse the dates and times.  It doesn't
> happen on every line, or every log file.
>
> You may have fixed this, I'm running version 1.22.0 from f-droid
> because I got an error installing the latest version they had.
> Android 5.02 on a Motorola Moto-e2
>
>
> On 10/5/15, Alan Corey <alan01346@gmail.com> wrote:
>> Does changing it in the GUI affect the way it's output?  I didn't try
>> that.
>>
>> The order is only important for "dumb" programs like Gnuplot, for
>> feeding to most real database programs like PostgreSQL, SqlLite, MS
>> Access the database can do the sort with an "order by" clause when
>> querying it.  Creating a new SqlLite database each day might be an
>> option, it's pretty universal and lightweight.
>>
>> In theory I thought Gnuplot could import your dates and times since
>> it's pretty flexible but I'm out of practice and gave up after an hour
>> or so of fighting with it.  Easier (and more fun) to just write
>> something.
>>
>> I was running a cron job on a unix machine that called hping and used
>> Gnuplot to make a plot each day but it didn't have access to fields
>> like dbm and asu.  The biggest problem was that when I was using the
>> network my loading affected the measurements.  The only internet
>> connection I've got is through a cell phone (or dial up), I use USB or
>> WiFi tethering off that.
>>
>> I don't get a lot of signal, but it seems like the internet
>> performance is even worse.  AT&T towers in a rural area, I'm not sure
>> what the root of the problem is.  Possibly just overloading.
>>
>> On 10/5/15, Carmen Alvarez <notifications@github.com> wrote:
>>> Hello ab1jx,
>>>
>>> Note that in the app, in the log view, you can tap on a column name to
>>> sort
>>> the data by that column.
>>>
>>> Could you please clarify something?  I'm not sure exactly what this
>>> request
>>> is for:
>>>
>>> 1) Do you want a new function to export the data to Gnuplot?
>>> 2) Do you want to modify one of the existing exports (CSV?) so that the
>>> export is sorted based on the column the user selected in the log view?
>>>
>>> Many thanks,
>>> Carmen
>>>
>>> ---
>>> Reply to this email directly or view it on GitHub:
>>> https://github.com/caarmen/network-monitor/issues/69#issuecomment-145625228
>>
>>
>> --
>> Credit is the root of all evil.  - AB1JX
>>
>
>
> --
> Credit is the root of all evil.  - AB1JX
>


-- 
Credit is the root of all evil.  - AB1JX

**Comment by ab1jx** [comment] 2015-10-06 15:14
OK, never mind, I didn't know the "raw" format is Sqlite 3.  That'll do nicely.

select timestamp, cell_signal_strength_dbm, gsm_full_cell_id,
ipv4_address from networkmonitor order by timestamp;

Works great, can even get to fields I didn't have in the GUI.  How
about making a new database each day (or week) with the date in the
file name?  Bummer about apps not being able to write to external SD
in Android 5+ but there is sort of a work around.  I posted this about
a week ago in F-Droid's forums.  No answers but there are links in it.
https://f-droid.org/forums/topic/app-to-unlock-external-sd-in-android-5/

On 10/5/15, Alan Corey <alan01346@gmail.com> wrote:
> And yes, changing the sort order in the GUI seems to change the CSV
> file sort order too.
>
> On 10/5/15, Alan Corey <alan01346@gmail.com> wrote:
>> Maybe I see why Gnuplot isn't working.  In some places in the CSV file
>> there's something like:
>>
>> 2015-10-0004
>> 05:46:0020,FAIL,FAIL,HSPAP,CONNECTED,1,1,0,CONNECTED,connecte
>> d,AT&T,310,410,1,0,-109,2,0,131779038,2010,51678,6994,33,92
>>
>> Notice the 4-digit day of month and also second.  This is what Gnuplot
>> complained about and it was also crashing a C program I wrote that
>> uses strptime() to try to parse the dates and times.  It doesn't
>> happen on every line, or every log file.
>>
>> You may have fixed this, I'm running version 1.22.0 from f-droid
>> because I got an error installing the latest version they had.
>> Android 5.02 on a Motorola Moto-e2
>>
>>
>> On 10/5/15, Alan Corey <alan01346@gmail.com> wrote:
>>> Does changing it in the GUI affect the way it's output?  I didn't try
>>> that.
>>>
>>> The order is only important for "dumb" programs like Gnuplot, for
>>> feeding to most real database programs like PostgreSQL, SqlLite, MS
>>> Access the database can do the sort with an "order by" clause when
>>> querying it.  Creating a new SqlLite database each day might be an
>>> option, it's pretty universal and lightweight.
>>>
>>> In theory I thought Gnuplot could import your dates and times since
>>> it's pretty flexible but I'm out of practice and gave up after an hour
>>> or so of fighting with it.  Easier (and more fun) to just write
>>> something.
>>>
>>> I was running a cron job on a unix machine that called hping and used
>>> Gnuplot to make a plot each day but it didn't have access to fields
>>> like dbm and asu.  The biggest problem was that when I was using the
>>> network my loading affected the measurements.  The only internet
>>> connection I've got is through a cell phone (or dial up), I use USB or
>>> WiFi tethering off that.
>>>
>>> I don't get a lot of signal, but it seems like the internet
>>> performance is even worse.  AT&T towers in a rural area, I'm not sure
>>> what the root of the problem is.  Possibly just overloading.
>>>
>>> On 10/5/15, Carmen Alvarez <notifications@github.com> wrote:
>>>> Hello ab1jx,
>>>>
>>>> Note that in the app, in the log view, you can tap on a column name to
>>>> sort
>>>> the data by that column.
>>>>
>>>> Could you please clarify something?  I'm not sure exactly what this
>>>> request
>>>> is for:
>>>>
>>>> 1) Do you want a new function to export the data to Gnuplot?
>>>> 2) Do you want to modify one of the existing exports (CSV?) so that the
>>>> export is sorted based on the column the user selected in the log view?
>>>>
>>>> Many thanks,
>>>> Carmen
>>>>
>>>> ---
>>>> Reply to this email directly or view it on GitHub:
>>>> https://github.com/caarmen/network-monitor/issues/69#issuecomment-145625228
>>>
>>>
>>> --
>>> Credit is the root of all evil.  - AB1JX
>>>
>>
>>
>> --
>> Credit is the root of all evil.  - AB1JX
>>
>
>
> --
> Credit is the root of all evil.  - AB1JX
>


-- 
Credit is the root of all evil.  - AB1JX

**Comment by caarmen** [comment] 2015-10-06 19:04
Hello.
> Works great, can even get to fields I didn't have in the GUI

Actually, you should be able to see these fields in the UI too.  In the log view, go to menu->Fields to monitor, and you can add or remove the fields you want to appear in the UI.

> Notice the 4-digit day of month and also second

Oops, looks like we have a bug :)  I'll take a look.

> How about making a new database each day (or week) with the date in the file name?

I'll think about this feature.  For now, there is an option to periodically send yourself the export (raw db, excel, whatever format you want) by e-mail.  I know it's not the same as having them all saved to the SD card.

> Bummer about apps not being able to write to external SD in Android 5+

I'll take a look at this.  I guess the problem with writing the main DB to a removable SD card is that if you do remove the card, all the data in network monitor will be lost.  Then, I guess if it's still running, the app may start to write to the "internal" SD card.  Then, if you put back in the removable SD card, the app would need some logic to merge the DB from both sources.  I should inform myself more on how apps are supposed to manage this :)

Could you share an example of the GnuPlot files you've created?  It might be interesting to add a new export format: to make the app export directly in a format you can load in GnuPlot directly.

**Comment by ab1jx** [comment] 2015-10-06 21:41
No, it's that it's including fields that don't show in the GUI that's
nice.  I might not want to look at them all the time but it's nice to
have them.  I didn't try the GPS data.  Around home I don't care about
it but I also belong to opencellid.org so I used to run Tower
Collector with my phone on my dash when I went somewhere, then upload
the results.  Even cell companies don't really know what their own
coverage is really like and trying to find out where a tower is
located from the number is like pulling hen's teeth.  I attached a CSV
from Tower Collector but you need a nasty long (36 characters) key to
upload.  Somebody else is collecting data I think too but this is free
to the public.  If you sign up you can download the database.  I used
a program not really meant for that to plot some.

The 4-digit thing might have been an email fluke, I only saw it once.

I don't think any sane person would try to remove an external SD card
without at least shutting down first.  As of Android 5 apps can't
write to external SD probably because Google is trying to promote
Cloud storage.  They relented and made it so you sort of can with
limitations.  I've got a phone with a 64 gig SD card and I can't
install any more apps because it mostly doesn't use it.  I've got 58
gigs free on it.

I've got an idea for a plot, I want to use different colors for the
different cell towers around here and plot points so you can see
signal vs time and which tower it came from.  Right now the catch is
that when I export your timestamps from sqlite I get numbers like
1444136521233, which looks like a unix time_t but the date in there is
Mon Jan 18 22:14:07 2038 so they're way out of range and Gnuplot
rejects them.  It's currently 1444167810.  There are 3 extra digits on
the end.
On 10/6/15, Carmen Alvarez <notifications@github.com> wrote:
> Hello.
>> Works great, can even get to fields I didn't have in the GUI
>
> Actually, you should be able to see these fields in the UI too.  In the log
> view, go to menu->Fields to monitor, and you can add or remove the fields
> you want to appear in the UI.
>
>> Notice the 4-digit day of month and also second
>
> Oops, looks like we have a bug :)  I'll take a look.
>
>> How about making a new database each day (or week) with the date in the
>> file name?
>
> I'll think about this feature.  For now, there is an option to periodically
> send yourself the export (raw db, excel, whatever format you want) by
> e-mail.  I know it's not the same as having them all saved to the SD card.
>
>> Bummer about apps not being able to write to external SD in Android 5+
>
> I'll take a look at this.  I guess the problem with writing the main DB to a
> removable SD card is that if you do remove the card, all the data in network
> monitor will be lost.  Then, I guess if it's still running, the app may
> start to write to the "internal" SD card.  Then, if you put back in the
> removable SD card, the app would need some logic to merge the DB from both
> sources.  I should inform myself more on how apps are supposed to manage
> this :)
>
> Could you share an example of the GnuPlot files you've created?  It might be
> interesting to add a new export format: to make the app export directly in a
> format you can load in GnuPlot directly.
>
>
>
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/caarmen/network-monitor/issues/69#issuecomment-145966938


-- 
Credit is the root of all evil.  - AB1JX

**Comment by ab1jx** [comment] 2015-10-07 17:12
I'm not sure it's useful but this is what I had in mind.  There are
lots of things you can do with Gnuplot, I think books have been
written about it.  This data is for part of a 2 day stretch and it
shows that at times none of the 4 cell towers plotted gives me a
usable signal.  That's in October with the leaves on the trees, it'll
probably be different in January.

In sqlite3 (the command line client) I did (for each cell tower):

.output 131778597.csv

select datetime(timestamp/1000,'unixepoch'), cell_signal_strength_dbm
from networkmonitor where gsm_full_cell_id=131778597 order by
timestamp;

Then I ran Gnuplot with this script (note you have to change the
xrange each time):

reset
set terminal gif size 1000,700
set output "logs.gif"
set style data dots
set timefmt "%Y-%m-%d %H:%M:%S"
set xdata time
set datafile sep '|'
set format x "%d_%H:%M"
set xrange["2015-10-04 05:50:00" : "2015-10-06 13:10:00"]
plot '131778597.csv' using 1:2 title '131778597',\
 '131778962.csv' using 1:2 title '131778962',\
 '131779032.csv' using 1:2 title '131779032',\
 '131779038.csv' using 1:2 title '131779038'

Looking at the plot, pick any horizontal position and see where the
highest dot plotted is, then read the signal dBm at the left.  In some
places it falls through all of them and at times I see no service at
all.

It was the
select datetime(timestamp/1000,'unixepoch')
that was the most trouble, I had to post a question on Stackoverflow
about it.  And it doesn't do what I'd expect, it gives times like
2015-10-04 08:12:33 but the timefmt line in the Gnuplot script tells
that what to expect.


On 10/6/15, Alan Corey <alan01346@gmail.com> wrote:
> No, it's that it's including fields that don't show in the GUI that's
> nice.  I might not want to look at them all the time but it's nice to
> have them.  I didn't try the GPS data.  Around home I don't care about
> it but I also belong to opencellid.org so I used to run Tower
> Collector with my phone on my dash when I went somewhere, then upload
> the results.  Even cell companies don't really know what their own
> coverage is really like and trying to find out where a tower is
> located from the number is like pulling hen's teeth.  I attached a CSV
> from Tower Collector but you need a nasty long (36 characters) key to
> upload.  Somebody else is collecting data I think too but this is free
> to the public.  If you sign up you can download the database.  I used
> a program not really meant for that to plot some.
>
> The 4-digit thing might have been an email fluke, I only saw it once.
>
> I don't think any sane person would try to remove an external SD card
> without at least shutting down first.  As of Android 5 apps can't
> write to external SD probably because Google is trying to promote
> Cloud storage.  They relented and made it so you sort of can with
> limitations.  I've got a phone with a 64 gig SD card and I can't
> install any more apps because it mostly doesn't use it.  I've got 58
> gigs free on it.
>
> I've got an idea for a plot, I want to use different colors for the
> different cell towers around here and plot points so you can see
> signal vs time and which tower it came from.  Right now the catch is
> that when I export your timestamps from sqlite I get numbers like
> 1444136521233, which looks like a unix time_t but the date in there is
> Mon Jan 18 22:14:07 2038 so they're way out of range and Gnuplot
> rejects them.  It's currently 1444167810.  There are 3 extra digits on
> the end.
> On 10/6/15, Carmen Alvarez <notifications@github.com> wrote:
>> Hello.
>>> Works great, can even get to fields I didn't have in the GUI
>>
>> Actually, you should be able to see these fields in the UI too.  In the
>> log
>> view, go to menu->Fields to monitor, and you can add or remove the fields
>> you want to appear in the UI.
>>
>>> Notice the 4-digit day of month and also second
>>
>> Oops, looks like we have a bug :)  I'll take a look.
>>
>>> How about making a new database each day (or week) with the date in the
>>> file name?
>>
>> I'll think about this feature.  For now, there is an option to
>> periodically
>> send yourself the export (raw db, excel, whatever format you want) by
>> e-mail.  I know it's not the same as having them all saved to the SD
>> card.
>>
>>> Bummer about apps not being able to write to external SD in Android 5+
>>
>> I'll take a look at this.  I guess the problem with writing the main DB to
>> a
>> removable SD card is that if you do remove the card, all the data in
>> network
>> monitor will be lost.  Then, I guess if it's still running, the app may
>> start to write to the "internal" SD card.  Then, if you put back in the
>> removable SD card, the app would need some logic to merge the DB from
>> both
>> sources.  I should inform myself more on how apps are supposed to manage
>> this :)
>>
>> Could you share an example of the GnuPlot files you've created?  It might
>> be
>> interesting to add a new export format: to make the app export directly in
>> a
>> format you can load in GnuPlot directly.
>>
>>
>>
>> ---
>> Reply to this email directly or view it on GitHub:
>> https://github.com/caarmen/network-monitor/issues/69#issuecomment-145966938
>
>
> --
> Credit is the root of all evil.  - AB1JX
>


-- 
Credit is the root of all evil.  - AB1JX

**Comment by ab1jx** [comment] 2015-10-07 19:57
Two variations on that.  Lines.gif shows the chronological progression
of signals from each tower, but I don't think there's a way to show 1
line and have it change colors depending on where the signal's coming
from.  linespoints.gif is the linespoints style which I use for most
data, but for the first one I set the style to dots because there are
so many they run into each other.

On 10/7/15, Alan Corey <alan01346@gmail.com> wrote:
> I'm not sure it's useful but this is what I had in mind.  There are
> lots of things you can do with Gnuplot, I think books have been
> written about it.  This data is for part of a 2 day stretch and it
> shows that at times none of the 4 cell towers plotted gives me a
> usable signal.  That's in October with the leaves on the trees, it'll
> probably be different in January.
>
> In sqlite3 (the command line client) I did (for each cell tower):
>
> .output 131778597.csv
>
> select datetime(timestamp/1000,'unixepoch'), cell_signal_strength_dbm
> from networkmonitor where gsm_full_cell_id=131778597 order by
> timestamp;
>
> Then I ran Gnuplot with this script (note you have to change the
> xrange each time):
>
> reset
> set terminal gif size 1000,700
> set output "logs.gif"
> set style data dots
> set timefmt "%Y-%m-%d %H:%M:%S"
> set xdata time
> set datafile sep '|'
> set format x "%d_%H:%M"
> set xrange["2015-10-04 05:50:00" : "2015-10-06 13:10:00"]
> plot '131778597.csv' using 1:2 title '131778597',\
>  '131778962.csv' using 1:2 title '131778962',\
>  '131779032.csv' using 1:2 title '131779032',\
>  '131779038.csv' using 1:2 title '131779038'
>
> Looking at the plot, pick any horizontal position and see where the
> highest dot plotted is, then read the signal dBm at the left.  In some
> places it falls through all of them and at times I see no service at
> all.
>
> It was the
> select datetime(timestamp/1000,'unixepoch')
> that was the most trouble, I had to post a question on Stackoverflow
> about it.  And it doesn't do what I'd expect, it gives times like
> 2015-10-04 08:12:33 but the timefmt line in the Gnuplot script tells
> that what to expect.
>
>
> On 10/6/15, Alan Corey <alan01346@gmail.com> wrote:
>> No, it's that it's including fields that don't show in the GUI that's
>> nice.  I might not want to look at them all the time but it's nice to
>> have them.  I didn't try the GPS data.  Around home I don't care about
>> it but I also belong to opencellid.org so I used to run Tower
>> Collector with my phone on my dash when I went somewhere, then upload
>> the results.  Even cell companies don't really know what their own
>> coverage is really like and trying to find out where a tower is
>> located from the number is like pulling hen's teeth.  I attached a CSV
>> from Tower Collector but you need a nasty long (36 characters) key to
>> upload.  Somebody else is collecting data I think too but this is free
>> to the public.  If you sign up you can download the database.  I used
>> a program not really meant for that to plot some.
>>
>> The 4-digit thing might have been an email fluke, I only saw it once.
>>
>> I don't think any sane person would try to remove an external SD card
>> without at least shutting down first.  As of Android 5 apps can't
>> write to external SD probably because Google is trying to promote
>> Cloud storage.  They relented and made it so you sort of can with
>> limitations.  I've got a phone with a 64 gig SD card and I can't
>> install any more apps because it mostly doesn't use it.  I've got 58
>> gigs free on it.
>>
>> I've got an idea for a plot, I want to use different colors for the
>> different cell towers around here and plot points so you can see
>> signal vs time and which tower it came from.  Right now the catch is
>> that when I export your timestamps from sqlite I get numbers like
>> 1444136521233, which looks like a unix time_t but the date in there is
>> Mon Jan 18 22:14:07 2038 so they're way out of range and Gnuplot
>> rejects them.  It's currently 1444167810.  There are 3 extra digits on
>> the end.
>> On 10/6/15, Carmen Alvarez <notifications@github.com> wrote:
>>> Hello.
>>>> Works great, can even get to fields I didn't have in the GUI
>>>
>>> Actually, you should be able to see these fields in the UI too.  In the
>>> log
>>> view, go to menu->Fields to monitor, and you can add or remove the
>>> fields
>>> you want to appear in the UI.
>>>
>>>> Notice the 4-digit day of month and also second
>>>
>>> Oops, looks like we have a bug :)  I'll take a look.
>>>
>>>> How about making a new database each day (or week) with the date in the
>>>> file name?
>>>
>>> I'll think about this feature.  For now, there is an option to
>>> periodically
>>> send yourself the export (raw db, excel, whatever format you want) by
>>> e-mail.  I know it's not the same as having them all saved to the SD
>>> card.
>>>
>>>> Bummer about apps not being able to write to external SD in Android 5+
>>>
>>> I'll take a look at this.  I guess the problem with writing the main DB
>>> to
>>> a
>>> removable SD card is that if you do remove the card, all the data in
>>> network
>>> monitor will be lost.  Then, I guess if it's still running, the app may
>>> start to write to the "internal" SD card.  Then, if you put back in the
>>> removable SD card, the app would need some logic to merge the DB from
>>> both
>>> sources.  I should inform myself more on how apps are supposed to manage
>>> this :)
>>>
>>> Could you share an example of the GnuPlot files you've created?  It
>>> might
>>> be
>>> interesting to add a new export format: to make the app export directly
>>> in
>>> a
>>> format you can load in GnuPlot directly.
>>>
>>>
>>>
>>> ---
>>> Reply to this email directly or view it on GitHub:
>>> https://github.com/caarmen/network-monitor/issues/69#issuecomment-145966938
>>
>>
>> --
>> Credit is the root of all evil.  - AB1JX
>>
>
>
> --
> Credit is the root of all evil.  - AB1JX
>


-- 
Credit is the root of all evil.  - AB1JX

**Comment by caarmen** [comment] 2015-11-29 17:48
I will close this ticket because the title of the ticket is "Allow changing sort order of data" and that was possible, as confirmed by this:
> And yes, changing the sort order in the GUI seems to change the CSV file sort order too.

Also, there was some discussion about gnuplot, and a gnuplot export feature has been added since.

Please feel free to open new tickets if there are still issues.   But please open one ticket per issue. It will just be easier for me to keep track of them if each ticket deals with one specific issue. :)

Many thanks :)

**Closed by caarmen** 2015-11-29 17:48 UTC
Labels: enhancement

**Comment by ab1jx** [comment] 2015-11-29 18:23
I saw you'd added that but I didn't try it yet.  I can think of a few other
things like being able to make a new database each day or week with the
date in the name. Also being able to save configurations and reload them,
like you might want 1 at home, a different one if you're travelling.  I'm
thinking a simple text rc file so it could be edited on a normal computer.
Among other things a list of fields and you can comment out with a # the
fields you don't want.

Can your source code be built with just Gradle and a jdk? I'm trying to get
set up for Android development but also changing hard drives in 2 machines
so it's low priority.  I'm pretty sure I need Linux, can't do it under my
usual OpenBSD.
